### ISSUE TITLE
Multiple self-signed CA

### ISSUE THREAD

**Issue by mojtabaimani** [kuberise/kuberise#41]
I would like to create two self signed CA: 
- one that is generated externally by the user and added as a secret to the cluster 
- and second one that is generated automatically inside the cluster 

The install.sh script will check for a ca.crt and ca.key file in .env/[PlatformName] folder in root folder. If it contains already the CA and private key, it will create a secret and deploy the CA to the cert-manager namespace. If not, it will generate a new crt and key and add them to the .env/[PlatformName] folder as well. 

## Tasks: 
- [x] Ignore all files and path including .env in .gitignore 
- [x] Generate CA if it doesn't exist in .env/[PlatformName] folder using openssl command
- [ ] Mention in the pre-requisite that openssl command is also needed to be available
- [ ] There should be possibility that people add the option --no-ca in the install.sh command to skip the self-signed certificate totally.
